### ISSUE TITLE
Package removal broken

### ISSUE THREAD

**Issue by kirankt** [defenseunicorns/uds-idam#91]
When the package deployment fails, running `zarf package remove uds-idam --confirm` doesn't clean up deployment. Currently only the ingressgateway resource gets removed. The helmrelease and the keycloak namespace and all its resources remain.

**Comment by UnicornChance** [comment]
This is also applicable to the uds bundling i believe. Would be beneficial, even if just for dev work, that `uds bundle remove` worked properly.

**Comment by UnicornChance** [comment]
@rjferguson21 Looking into this in conjunction with [this PR](https://github.com/defenseunicorns/uds-idam/pull/104). I am able to bundle deploy and bundle remove everything successfully. However, after removing if deployed again with no changes to the bundle keycloak fails to deploy because it can't connect to the DB. I believe this has something to do with the remove process leaving secrets and configmaps from original deployment.

**Comment by UnicornChance** [comment]
@rjferguson21 @kirankt this should be resolved in the PR mentioned in the previous comment. I added an [additional commit](https://github.com/defenseunicorns/uds-idam/pull/104/commits/889dc95c5a22b96ac64e16d857704f40897b745a) for removing the keycloak namespace which helps to resolve the bundle remove and zarf package remove problems we've been seeing.
